FROM docker.elastic.co/beats/packetbeat:7.17.22

COPY packetbeat.yml /usr/share/packetbeat/packetbeat.yml

USER root
RUN chown root:packetbeat /usr/share/packetbeat/packetbeat.yml && \
    chmod go-w /usr/share/packetbeat/packetbeat.yml

USER packetbeat