FROM docker.elastic.co/beats/metricbeat:7.17.22

COPY metricbeat.yml /usr/share/metricbeat/metricbeat.yml

USER root
RUN chown root:metricbeat /usr/share/metricbeat/metricbeat.yml && \
    chmod go-w /usr/share/metricbeat/metricbeat.yml

USER metricbeat