FROM docker.elastic.co/beats/heartbeat:7.17.22

COPY heartbeat.yml /usr/share/heartbeat/heartbeat.yml

USER root
RUN chown root:heartbeat /usr/share/heartbeat/heartbeat.yml && \
    chmod go-w /usr/share/heartbeat/heartbeat.yml

USER heartbeat